# Generated by Django 3.2.6 on 2021-08-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='ComentCrm',
        ),
    ]
